### https://machinelearningmastery.com/k-fold-cross-validation/

In [53]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import numpy as np
import matplotlib

import matplotlib.pyplot as plt
from sklearn.datasets import load_digits

digits = load_digits()

In [54]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target, test_size=0.3)

In [55]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/Users/klrao/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9481481481481482

In [56]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9814814814814815

In [57]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9574074074074074

In [58]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [59]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [60]:
digits.data[0] , digits.target[0]

(array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]),
 0)

In [61]:
X = [[1,2,3,4],
    [8,9,10,12],
    [11,12,23,34],
    [111,32,35,14],
    [89,91,109,102],
    [112,412,234,344]]

y = [1,0,1,1,0,1]



In [62]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [63]:
import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=2)
kf.get_n_splits(X)
print(kf)
i = 0
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(f'{i:{20}} {X_train}')
    i+=1

KFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [2 3] TEST: [0 1]
                   0 [[1 2]
 [3 4]]
TRAIN: [0 1] TEST: [2 3]
                   1 [[1 2]
 [3 4]]


In [64]:
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2, 3] , [3, 2, 1] , [1, 2, 3] , [3, 2, 1] ])
y = np.array([0, 0, 1, 1])

skf = StratifiedKFold(n_splits=2)

print(X.shape,y.shape)
print(skf.get_n_splits(X,y))
print(skf)
i = 0
for train_index, test_index in skf.split(X,y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(f'{i:{20}} {X_train}')
    i+=1

(4, 3) (4,)
2
StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [1 3] TEST: [0 2]
                   0 [[3 2 1]
 [3 2 1]]
TRAIN: [0 2] TEST: [1 3]
                   1 [[1 2 3]
 [1 2 3]]


In [65]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = np.array([[11, 21], [31, 41], [51, 61], [71, 81],[91,101]])
y = np.array([1, 1, 0, 0,2])
skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(X,y)
print(skf)
i = 0
for train_index, test_index in skf.split(X,y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(f'{X_train}'+'=>'+f'{X_test}')
    i+=1

StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
[[31 41]
 [71 81]]=>[[ 11  21]
 [ 51  61]
 [ 91 101]]
[[ 11  21]
 [ 51  61]
 [ 91 101]]=>[[31 41]
 [71 81]]


/Users/klrao/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(("The least populated class in y has only %d"


In [77]:
scores = []
for train_index, test_index in kf.split(digits.data):
    #print( train_index, test_index)
    
    X_train,X_test = digits.data[train_index],digits.data[test_index]
    y_train,y_test = digits.target[train_index],digits.target[test_index]
    svm.fit(X_train,y_train)
    scores.append(svm.score(X_test,y_test))
    lr.fit(X_train,y_train)
    scores.append(lr.score(X_test,y_test))
    rf.fit(X_train,y_train)
    scores.append(rf.score(X_test,y_test))
    
    print(svm.score(X_test,y_test))
    print(lr.score(X_test,y_test))
    print(rf.score(X_test,y_test))
    

/Users/klrao/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9510567296996663
0.8943270300333704
0.9043381535038932
0.9610244988864143
0.9276169265033407
0.9242761692650334


/Users/klrao/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [78]:
scores

[0.9510567296996663,
 0.8943270300333704,
 0.9043381535038932,
 0.9610244988864143,
 0.9276169265033407,
 0.9242761692650334]

In [79]:

from sklearn.model_selection import cross_val_score

In [80]:
cross_val_score(lr, digits.data, digits.target,cv=2)

/Users/klrao/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/klrao/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regr

array([0.89988877, 0.93095768])

In [81]:
cross_val_score(rf, digits.data, digits.target,cv=2)

array([0.92658509, 0.922049  ])

In [82]:
cross_val_score(svm, digits.data, digits.target,cv=2)

array([0.95439377, 0.95991091])

In [84]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target,cv=10)

array([0.89444444, 0.97777778, 0.93333333, 0.89444444, 0.93333333,
       0.97222222, 0.96111111, 0.95530726, 0.94972067, 0.93296089])

In [85]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target,cv=10)

array([0.91666667, 0.97222222, 0.92777778, 0.91111111, 0.95      ,
       0.96666667, 0.98888889, 0.95530726, 0.93296089, 0.9273743 ])

In [86]:
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target,cv=10)

array([0.89444444, 0.97222222, 0.95555556, 0.92222222, 0.95555556,
       0.96111111, 0.98888889, 0.95530726, 0.9273743 , 0.93296089])

In [87]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target,cv=10)
np.average(scores1)

0.9499193047796399

In [88]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target,cv=10)
np.average(scores2)

0.9443482309124767

In [89]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target,cv=10)
np.average(scores3)

0.9426784605834884

In [90]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=70), digits.data, digits.target,cv=10)
np.average(scores4)

0.9471229050279328

In [91]:
X = np.array([[1, 2, 3] , [3, 2, 1] , [1, 2, 3] , [3, 2, 1] ])
kf1 = KFold(n_splits=4)

In [96]:
kf1 = KFold(n_splits=3)
for t_idx,te_idx in kf1.split(X):
    print(t_idx,te_idx)
    

[2 3] [0 1]
[0 1 3] [2]
[0 1 2] [3]


In [102]:
X = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

print("<------ Splits = k ------->")   
kf2 = KFold(n_splits=6)
for tr_idx,te_idx in kf2.split(X):
    print(tr_idx,te_idx)
print("<------ Splits = k - 1 ------->")    
kf3 = KFold(n_splits=5)
for tr3_idx,te3_idx in kf3.split(X):
    print(X[tr3_idx],X[te3_idx])

<------ Splits = k ------->
[1 2 3 4 5] [0]
[0 2 3 4 5] [1]
[0 1 3 4 5] [2]
[0 1 2 4 5] [3]
[0 1 2 3 5] [4]
[0 1 2 3 4] [5]
<------ Splits = k - 1 ------->
[0.3 0.4 0.5 0.6] [0.1 0.2]
[0.1 0.2 0.4 0.5 0.6] [0.3]
[0.1 0.2 0.3 0.5 0.6] [0.4]
[0.1 0.2 0.3 0.4 0.6] [0.5]
[0.1 0.2 0.3 0.4 0.5] [0.6]
